name: publish the Docker image to the github
on:
  release:
          types: [published]
jobs: 
 push_to_registry:
         name: push docker images to the Docker hub
         runs-on: ubuntu-latest
         steps: 
         - name: check out th repo
           uses: actions/checkout@v2
         - name: push to docker hub
           uses: docker/build-push-action@v2
           with:
              username: ${{secrets.DOCKER_USERNAME}}
              password: ${{secrets.DOCKER_PASSWORD}}
              repository: https://hub.docker.com/u/surajmachamasi/ 
              tag_with_ref: true        



